select SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME,
	USER_NAME AS SCHEMA_NAME, 
	PROXY_NAME, 
	AUDIT_OPTION, 
	SUCCESS, 
	FAILURE,
	SYS_CONTEXT ('USERENV','DB_NAME') || USER_NAME AS ROWKEY
from dba_stmt_audit_opts;