SELECT OWNER, JOB_NAME
, JOB_SUBNAME, JOB_STYLE, JOB_CREATOR, PROGRAM_OWNER, PROGRAM_NAME, JOB_TYPE, JOB_ACTION
, SCHEDULE_NAME, SCHEDULE_TYPE
, START_DATE, REPEAT_INTERVAL
, LAST_START_DATE
--, LAST_RUN_DURATION
, NEXT_RUN_DATE
, COMMENTS 
FROM ALL_SCHEDULER_JOBS;