select SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME,
	OWNER AS SCHEMA_NAME,
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE,
	DATA_LENGTH,
	CHAR_LENGTH,
	'' AS IDENTITY_COLUMN,
	DATA_DEFAULT,
	'' AS COLLATION,
	SYS_CONTEXT ('USERENV','DB_NAME') || OWNER AS ROWKEY
from DBA_TAB_COLUMNS 
where OWNER NOT IN ('SYS', 'SYSTEM', 'ANONYMOUS', 'CTXSYS', 'DBSNMP', 'LBACSYS', 'MDSYS', 'OLAPSYS', 'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'SCOTT', 'WKSYS', 'WMSYS', 'XDB', 
 'DVSYS', 'EXFSYS', 'MGMT_VIEW', 'ORDDATA', 'OWBSYS', 'ORDPLUGINS', 'SYSMAN', 'WKSYS', 'WKPROXY', 'AUDSYS', 'GSMADMIN_INTERNAL', 'DBSFWUSER', 'OJVMSYS', 'APPQOSSYS', 'REMOTE_SCHEDULER_AGENT', 'DVF', 'ORACLE_OCM', 'PUBLIC');