SELECT SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME, 
	"'NUM_CPUS'" AS NUM_CPUS,
	"'AVG_IDLE_TIME'" AS AVG_IDLE_TIME,
	"'AVG_BUSY_TIME'" AS AVG_BUSY_TIME,
	"'NUM_CPU_CORES'" AS NUM_CPU_CORES,
	"'NUM_CPU_SOCKETS'" AS NUM_CPU_SOCKETS,
	"'PHYSICAL_MEMORY_BYTES'" AS PHYSICAL_MEMORY_BYTES,
	"'FREE_MEMORY_BYTES'" AS FREE_MEMORY_BYTES
FROM (
	select STAT_NAME,
		TO_CHAR(VALUE) AS VALUE
	from V$OSSTAT 
	where stat_name IN (
		'NUM_CPUS',
		'AVG_IDLE_TIME',
		'AVG_BUSY_TIME',
		'NUM_CPU_CORES',
		'NUM_CPU_SOCKETS',
		'PHYSICAL_MEMORY_BYTES',
		'FREE_MEMORY_BYTES'
	)
)
PIVOT
(
	MAX(VALUE)
	FOR stat_name IN (
		'NUM_CPUS',
		'AVG_IDLE_TIME',
		'AVG_BUSY_TIME',
		'NUM_CPU_CORES',
		'NUM_CPU_SOCKETS',
		'PHYSICAL_MEMORY_BYTES',
		'FREE_MEMORY_BYTES'
	)
)
;