SELECT SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME, 
	OWNER AS SCHEMA_NAME,
	TABLE_NAME,
	COLUMN_NAME,
	ENCRYPTION_ALG,
	SYS_CONTEXT ('USERENV','DB_NAME') || OWNER AS ROWKEY
FROM dba_encrypted_columns;

