SELECT SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME,
	OWNER as SCHEMA_NAME,
	SYNONYM_NAME,
	TABLE_OWNER,
	TABLE_NAME,
	DB_LINK 
	, SYS_CONTEXT ('USERENV','DB_NAME') || OWNER AS ROWKEY
FROM DBA_SYNONYMS 
WHERE OWNER = 'PUBLIC' 
	and table_name LIKE 'UTL_MAIL';