SELECT sys_context('USERENV','INSTANCE_NAME') AS INSTANCE_NAME,
	OWNER as SCHEMA_NAME,
	SYNONYM_NAME,
	TABLE_OWNER,
	TABLE_NAME,
	DB_LINK 
	, SYS_CONTEXT('USERENV','INSTANCE_NAME') || OWNER AS ROWKEY
FROM DBA_SYNONYMS 
WHERE OWNER = 'PUBLIC' 
	and table_name LIKE 'UTL_MAIL';