select SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME,
	i.OWNER AS SCHEMA_NAME,
	i.INDEX_NAME,
    i.INDEX_TYPE,
	i.TABLE_NAME,
	i.UNIQUENESS,
  COUNT(c.COLUMN_NAME) AS COLUMN_COUNT,
  sum(s.bytes)/1024/1024 AS STORAGE_USED_MB,
	SYS_CONTEXT ('USERENV','DB_NAME') || i.OWNER AS ROWKEY
from dba_indexes i
  INNER JOIN DBA_IND_COLUMNS c ON (i.OWNER = c.INDEX_OWNER AND i.INDEX_NAME = c.INDEX_NAME)
  INNER JOIN DBA_SEGMENTS s ON (i.OWNER = s.OWNER AND i.INDEX_NAME = s.SEGMENT_NAME AND s.SEGMENT_TYPE = 'INDEX')
WHERE i.OWNER NOT IN ('SYS', 'SYSTEM', 'ANONYMOUS', 'CTXSYS', 'DBSNMP', 'LBACSYS', 'MDSYS', 'OLAPSYS', 'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'SCOTT', 'WKSYS', 'WMSYS', 'XDB', 
    'DVSYS', 'EXFSYS', 'MGMT_VIEW', 'ORDDATA', 'OWBSYS', 'ORDPLUGINS', 'SYSMAN', 'WKSYS', 'WKPROXY', 'AUDSYS', 'GSMADMIN_INTERNAL', 'DBSFWUSER', 'OJVMSYS', 'APPQOSSYS', 'REMOTE_SCHEDULER_AGENT', 'DVF', 'ORACLE_OCM')
GROUP BY SYS_CONTEXT ('USERENV','DB_NAME'), 
  i.OWNER,
 	i.INDEX_NAME,
    i.INDEX_TYPE,
	i.TABLE_NAME,
	i.UNIQUENESS
;