select sys_context('USERENV','INSTANCE_NAME') AS INSTANCE_NAME, 
	T.OWNER AS SCHEMA_NAME,
	T.TABLE_NAME,
	T.PARTITIONED,
	SUM(T.NUM_ROWS) AS ROW_COUNT,
	ROUND(SUM(BYTES)/1024/1024,4) AS TABLE_SIZE_MB,
	ROUND(SUM(BYTES)/1024/1024/1024,5) AS TABLE_SIZE_GB,
	ROUND(SUM(BYTES)/1024/1024/1024/1024,8) AS TABLE_SIZE_TB,
	SYS_CONTEXT('USERENV','INSTANCE_NAME') || T.OWNER AS ROWKEY
FROM DBA_TABLES T
	INNER JOIN DBA_SEGMENTS S 
		ON T.OWNER = S.OWNER AND T.TABLE_NAME = S.SEGMENT_NAME
WHERE t.OWNER NOT IN ('SYS', 'SYSTEM', 'ANONYMOUS', 'CTXSYS', 'DBSNMP', 'LBACSYS', 'MDSYS', 'OLAPSYS', 'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'SCOTT', 'WKSYS', 'WMSYS', 'XDB', 
 'DVSYS', 'EXFSYS', 'MGMT_VIEW', 'ORDDATA', 'OWBSYS', 'ORDPLUGINS', 'SYSMAN', 'WKSYS', 'WKPROXY', 'AUDSYS', 'GSMADMIN_INTERNAL', 'DBSFWUSER', 'OJVMSYS', 'APPQOSSYS', 'REMOTE_SCHEDULER_AGENT', 'DVF', 'ORACLE_OCM', 'PUBLIC')
GROUP BY SYS_CONTEXT('USERENV','INSTANCE_NAME'), T.OWNER, T.TABLE_NAME, T.PARTITIONED;