select 
	SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME, 
	TABLE_OWNER as SCHEMA_NAME, 
	TABLE_NAME, 
	PARTITION_NAME,
	SUM(NUM_ROWS) ROW_COUNT,
	ROUND(SUM(AVG_ROW_LEN*NUM_ROWS)/1024/1024,2) AS PARTITIONSIZE_MB,
	ROUND(SUM(AVG_ROW_LEN*NUM_ROWS)/1024/1024/1024,5) AS PARTITIONSIZE_GB,
	ROUND(SUM(AVG_ROW_LEN*NUM_ROWS)/1024/1024/1024/1024,8) AS PARTITIONSIZE_TB,
	SYS_CONTEXT ('USERENV','DB_NAME') || TABLE_OWNER AS ROWKEY
FROM DBA_TAB_PARTITIONS
WHERE TABLE_OWNER NOT IN ('SYS', 'SYSTEM', 'ANONYMOUS', 'CTXSYS', 'DBSNMP', 'LBACSYS', 'MDSYS', 'OLAPSYS', 'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'SCOTT', 'WKSYS', 'WMSYS', 'XDB', 
'DVSYS', 'EXFSYS', 'MGMT_VIEW', 'ORDDATA', 'OWBSYS', 'ORDPLUGINS', 'SYSMAN', 'WKSYS', 'WKPROXY', 'AUDSYS', 'GSMADMIN_INTERNAL', 'DBSFWUSER', 'OJVMSYS', 'APPQOSSYS', 'REMOTE_SCHEDULER_AGENT', 'DVF', 'ORACLE_OCM', 'PUBLIC')
group by SYS_CONTEXT ('USERENV','DB_NAME'), TABLE_OWNER, TABLE_NAME, PARTITION_NAME;



