select SYS_CONTEXT ('USERENV','DB_NAME') AS INSTANCE_NAME,
	USERNAME AS SCHEMA_NAME, 
	USER_ID, 
	CREATED, 
	'' AS DEFAULT_COLLATION,
	SYS_CONTEXT ('USERENV','DB_NAME') || USERNAME AS ROWKEY
from DBA_USERS
where username not in ('SYS', 'SYSTEM', 'ANONYMOUS', 'CTXSYS', 'DBSNMP', 'LBACSYS', 'MDSYS', 'OLAPSYS', 'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'SCOTT', 'WKSYS', 'WMSYS', 'XDB', 
  'DVSYS', 'EXFSYS', 'MGMT_VIEW', 'ORDDATA', 'OWBSYS', 'ORDPLUGINS', 'SYSMAN', 'WKSYS', 'WKPROXY', 'AUDSYS', 'GSMADMIN_INTERNAL', 'DBSFWUSER', 'OJVMSYS', 'APPQOSSYS', 'REMOTE_SCHEDULER_AGENT', 'DVF', 'ORACLE_OCM');